name: Build & Deploy TorizonCore
on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    container:
      image: torizonextras/torizon-dev:next
    steps:
      - uses: actions/checkout@v3

      - name: Get Host Absolute Workspace Path
        run: |
          echo "${{ github.workspace }}" >> abs-path
          cat abs-path

      - name: Initial Setup
        shell: xonsh {0}
        env:
          TORIZON_ARCH: ""
          DOCKER_PSSWD: ${{ secrets.DOCKER_PSSWD }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          import os
          import json

          with open(".vscode/settings.json") as f:
              settings = json.load(f)
              os.environ["TORIZON_ARCH"] = settings["torizon_arch"]
              if os.environ["TORIZON_ARCH"] == "aarch64":
                  os.environ["TORIZON_ARCH"] = "arm64"
              if os.environ["TORIZON_ARCH"] == "armhf":
                  os.environ["TORIZON_ARCH"] = "arm"

          with open(os.environ["GITHUB_ENV"], "a") as f:
              f.write(f"TORIZON_ARCH={os.environ['TORIZON_ARCH']}\n")

          xonsh ./.vscode/tasks.xsh run validate-pipeline-settings

      - name: Decode Credentials
        env:
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          echo $PLATFORM_CREDENTIALS | base64 -d > credentials.zip

      - name: Create and Publish Image
        shell: xonsh {0}
        env:
          TASKS_ITERATIVE: "False"
          TASKS_OVERRIDE_ENV: "False"
          DOCKER_PSSWD: ${{ secrets.DOCKER_PSSWD }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        run: |
          xonsh ./.vscode/tasks.xsh run docker-login
          xonsh ./.vscode/tasks.xsh run run-torizon-binfmt
          xonsh ./.vscode/tasks.xsh run tcb-platform-publish

      - name: Deploy Application
        shell: xonsh {0}
        env:
          TASKS_ITERATIVE: "False"
          TASKS_OVERRIDE_ENV: "False"
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          xonsh ./.vscode/tasks.xsh run platform-update-fleet

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-prod
          path: |
            docker-compose.prod.yml
            docker-compose.prod.lock.yml
